// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: epochdb.proto

// THE PRIMARY REMOTE API (user ruling 2026-08-12: "gRPC should be the best way
// to access it"). It is a PEER adapter over the core query layer (rpc.Server's
// direct methods), never a proxy to JSON-RPC.
//
// BYTES ARE VERBATIM CONSENSUS RLP wherever the corpus stores RLP: a header, a
// transaction. Nothing is re-serialized into a field-by-field shape that could
// disagree with the stored bytes, and a caller that wants fields decodes with
// the EVM library it already links. Numbers that are not RLP (heights, TxNums,
// gas) are plain integers, and big integers travel as big-endian bytes.

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadRequest) Reset() {
	*x = HeadRequest{}
	mi := &file_epochdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadRequest) ProtoMessage() {}

func (x *HeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadRequest.ProtoReflect.Descriptor instead.
func (*HeadRequest) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{0}
}

type HeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"` // last block served: `latest`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Accepted      uint64                 `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"` // the follower's accepted head: `pending`
	Settled       uint64                 `protobuf:"varint,5,opt,name=settled,proto3" json:"settled,omitempty"`   // SAE-settled: `safe`/`finalized`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadResponse) Reset() {
	*x = HeadResponse{}
	mi := &file_epochdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadResponse) ProtoMessage() {}

func (x *HeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadResponse.ProtoReflect.Descriptor instead.
func (*HeadResponse) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{1}
}

func (x *HeadResponse) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *HeadResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *HeadResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeadResponse) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *HeadResponse) GetSettled() uint64 {
	if x != nil {
		return x.Settled
	}
	return 0
}

// BlockRequest names a block by hash if hash is set, by number otherwise.
// full=false answers with the header and the transaction COUNT only.
type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Full          bool                   `protobuf:"varint,3,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_epochdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{2}
}

func (x *BlockRequest) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockRequest) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	HeaderRlp     []byte                 `protobuf:"bytes,3,opt,name=header_rlp,json=headerRlp,proto3" json:"header_rlp,omitempty"` // the stored consensus bytes, verbatim
	TxCount       uint32                 `protobuf:"varint,4,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	TxRlp         [][]byte               `protobuf:"bytes,5,rep,name=tx_rlp,json=txRlp,proto3" json:"tx_rlp,omitempty"` // full=true only, in block order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_epochdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{3}
}

func (x *BlockResponse) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockResponse) GetHeaderRlp() []byte {
	if x != nil {
		return x.HeaderRlp
	}
	return nil
}

func (x *BlockResponse) GetTxCount() uint32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *BlockResponse) GetTxRlp() [][]byte {
	if x != nil {
		return x.TxRlp
	}
	return nil
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_epochdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// found=false is a clean "unknown transaction", never an error.
type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	TxRlp         []byte                 `protobuf:"bytes,2,opt,name=tx_rlp,json=txRlp,proto3" json:"tx_rlp,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Index         uint32                 `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Receipt       *Receipt               `protobuf:"bytes,6,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Frames        []*Frame               `protobuf:"bytes,7,rep,name=frames,proto3" json:"frames,omitempty"` // the STORED call frames, never a re-execution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_epochdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *TransactionResponse) GetTxRlp() []byte {
	if x != nil {
		return x.TxRlp
	}
	return nil
}

func (x *TransactionResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *TransactionResponse) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *TransactionResponse) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TransactionResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *TransactionResponse) GetFrames() []*Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

type Receipt struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            uint64                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	GasUsed           uint64                 `protobuf:"varint,2,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	CumulativeGasUsed uint64                 `protobuf:"varint,3,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty"`
	ContractAddress   []byte                 `protobuf:"bytes,4,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // empty unless the tx created one
	Logs              []*Log                 `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_epochdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{6}
}

func (x *Receipt) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Receipt) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *Receipt) GetCumulativeGasUsed() uint64 {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return 0
}

func (x *Receipt) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *Receipt) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics        [][]byte               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxHash        []byte                 `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TxIndex       uint32                 `protobuf:"varint,6,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	Index         uint32                 `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_epochdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{7}
}

func (x *Log) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Log) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Log) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *Log) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *Log) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// Frame is one stored call frame in enter order. kind is the vm.OpCode of the
// call that opened it.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          uint32                 `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Depth         uint32                 `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	From          []byte                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"` // big-endian, empty for none
	Gas           uint64                 `protobuf:"varint,6,opt,name=gas,proto3" json:"gas,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,7,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Failed        bool                   `protobuf:"varint,8,opt,name=failed,proto3" json:"failed,omitempty"`
	Input         []byte                 `protobuf:"bytes,9,opt,name=input,proto3" json:"input,omitempty"`
	Output        []byte                 `protobuf:"bytes,10,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_epochdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{8}
}

func (x *Frame) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Frame) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Frame) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Frame) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Frame) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Frame) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *Frame) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *Frame) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *Frame) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Frame) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

// CallRequest is an eth_call at a height. height 0 means the serving head.
type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          []byte                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`       // empty is a contract creation
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // big-endian
	Gas           uint64                 `protobuf:"varint,4,opt,name=gas,proto3" json:"gas,omitempty"`    // 0 takes the server's cap
	GasPrice      []byte                 `protobuf:"bytes,5,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Height        uint64                 `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_epochdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{9}
}

func (x *CallRequest) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CallRequest) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CallRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CallRequest) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *CallRequest) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *CallRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CallRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_epochdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{10}
}

func (x *CallResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

// StateRequest reads one account at a height, and one storage slot of it when
// slot is set. height 0 means the serving head.
type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Slot          []byte                 `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	WithCode      bool                   `protobuf:"varint,4,opt,name=with_code,json=withCode,proto3" json:"with_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_epochdb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{11}
}

func (x *StateRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *StateRequest) GetSlot() []byte {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *StateRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *StateRequest) GetWithCode() bool {
	if x != nil {
		return x.WithCode
	}
	return false
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Balance       []byte                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"` // big-endian
	CodeHash      []byte                 `protobuf:"bytes,3,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	Code          []byte                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"` // with_code only
	SlotValue     []byte                 `protobuf:"bytes,5,opt,name=slot_value,json=slotValue,proto3" json:"slot_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_epochdb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{12}
}

func (x *StateResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *StateResponse) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *StateResponse) GetCodeHash() []byte {
	if x != nil {
		return x.CodeHash
	}
	return nil
}

func (x *StateResponse) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *StateResponse) GetSlotValue() []byte {
	if x != nil {
		return x.SlotValue
	}
	return nil
}

// SearchRequest is KEYSET paging over the address's posting rows: cursor is
// the TxNum to continue from (inclusive), 0 meaning the end the walk starts
// at. Newest-first unless ascending.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Cursor        uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Ascending     bool                   `protobuf:"varint,4,opt,name=ascending,proto3" json:"ascending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_epochdb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{13}
}

func (x *SearchRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SearchRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*AddrHit             `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	More          bool                   `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"` // exact, not guessed: the walk reads one row past the page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_epochdb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{14}
}

func (x *SearchResponse) GetHits() []*AddrHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

type AddrHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxNum         uint64                 `protobuf:"varint,1,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Roles         uint32                 `protobuf:"varint,4,opt,name=roles,proto3" json:"roles,omitempty"` // store.Role* bits: sender, recipient, created, emitter, frame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddrHit) Reset() {
	*x = AddrHit{}
	mi := &file_epochdb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddrHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrHit) ProtoMessage() {}

func (x *AddrHit) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrHit.ProtoReflect.Descriptor instead.
func (*AddrHit) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{15}
}

func (x *AddrHit) GetTxNum() uint64 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

func (x *AddrHit) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AddrHit) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *AddrHit) GetRoles() uint32 {
	if x != nil {
		return x.Roles
	}
	return 0
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromBlock     uint64                 `protobuf:"varint,1,opt,name=from_block,json=fromBlock,proto3" json:"from_block,omitempty"`
	ToBlock       uint64                 `protobuf:"varint,2,opt,name=to_block,json=toBlock,proto3" json:"to_block,omitempty"`
	Addresses     [][]byte               `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Topics        []*TopicSet            `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"` // position i matches topic i; empty set matches any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_epochdb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{16}
}

func (x *LogsRequest) GetFromBlock() uint64 {
	if x != nil {
		return x.FromBlock
	}
	return 0
}

func (x *LogsRequest) GetToBlock() uint64 {
	if x != nil {
		return x.ToBlock
	}
	return 0
}

func (x *LogsRequest) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *LogsRequest) GetTopics() []*TopicSet {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TopicSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicSet) Reset() {
	*x = TopicSet{}
	mi := &file_epochdb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSet) ProtoMessage() {}

func (x *TopicSet) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSet.ProtoReflect.Descriptor instead.
func (*TopicSet) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{17}
}

func (x *TopicSet) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*Log                 `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_epochdb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epochdb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_epochdb_proto_rawDescGZIP(), []int{18}
}

func (x *LogsResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_epochdb_proto protoreflect.FileDescriptor

const file_epochdb_proto_rawDesc = "" +
	"\n" +
	"\repochdb.proto\x12\n" +
	"epochdb.v0\"\r\n" +
	"\vHeadRequest\"\x8e\x01\n" +
	"\fHeadResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\x04R\baccepted\x12\x18\n" +
	"\asettled\x18\x05 \x01(\x04R\asettled\"N\n" +
	"\fBlockRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x12\n" +
	"\x04full\x18\x03 \x01(\bR\x04full\"\x8c\x01\n" +
	"\rBlockResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x1d\n" +
	"\n" +
	"header_rlp\x18\x03 \x01(\fR\theaderRlp\x12\x19\n" +
	"\btx_count\x18\x04 \x01(\rR\atxCount\x12\x15\n" +
	"\x06tx_rlp\x18\x05 \x03(\fR\x05txRlp\"(\n" +
	"\x12TransactionRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\xf4\x01\n" +
	"\x13TransactionResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x15\n" +
	"\x06tx_rlp\x18\x02 \x01(\fR\x05txRlp\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\fR\tblockHash\x12\x14\n" +
	"\x05index\x18\x05 \x01(\rR\x05index\x12-\n" +
	"\areceipt\x18\x06 \x01(\v2\x13.epochdb.v0.ReceiptR\areceipt\x12)\n" +
	"\x06frames\x18\a \x03(\v2\x11.epochdb.v0.FrameR\x06frames\"\xbc\x01\n" +
	"\aReceipt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x04R\x06status\x12\x19\n" +
	"\bgas_used\x18\x02 \x01(\x04R\agasUsed\x12.\n" +
	"\x13cumulative_gas_used\x18\x03 \x01(\x04R\x11cumulativeGasUsed\x12)\n" +
	"\x10contract_address\x18\x04 \x01(\fR\x0fcontractAddress\x12#\n" +
	"\x04logs\x18\x05 \x03(\v2\x0f.epochdb.v0.LogR\x04logs\"\xb8\x01\n" +
	"\x03Log\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\fR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12\x17\n" +
	"\atx_hash\x18\x05 \x01(\fR\x06txHash\x12\x19\n" +
	"\btx_index\x18\x06 \x01(\rR\atxIndex\x12\x14\n" +
	"\x05index\x18\a \x01(\rR\x05index\"\xde\x01\n" +
	"\x05Frame\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\rR\x04kind\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\rR\x05depth\x12\x12\n" +
	"\x04from\x18\x03 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x10\n" +
	"\x03gas\x18\x06 \x01(\x04R\x03gas\x12\x19\n" +
	"\bgas_used\x18\a \x01(\x04R\agasUsed\x12\x16\n" +
	"\x06failed\x18\b \x01(\bR\x06failed\x12\x14\n" +
	"\x05input\x18\t \x01(\fR\x05input\x12\x16\n" +
	"\x06output\x18\n" +
	" \x01(\fR\x06output\"\xa2\x01\n" +
	"\vCallRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x10\n" +
	"\x03gas\x18\x04 \x01(\x04R\x03gas\x12\x1b\n" +
	"\tgas_price\x18\x05 \x01(\fR\bgasPrice\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x16\n" +
	"\x06height\x18\a \x01(\x04R\x06height\"&\n" +
	"\fCallResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\"q\n" +
	"\fStateRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\fR\x04slot\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12\x1b\n" +
	"\twith_code\x18\x04 \x01(\bR\bwithCode\"\x8f\x01\n" +
	"\rStateResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12\x18\n" +
	"\abalance\x18\x02 \x01(\fR\abalance\x12\x1b\n" +
	"\tcode_hash\x18\x03 \x01(\fR\bcodeHash\x12\x12\n" +
	"\x04code\x18\x04 \x01(\fR\x04code\x12\x1d\n" +
	"\n" +
	"slot_value\x18\x05 \x01(\fR\tslotValue\"u\n" +
	"\rSearchRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x1c\n" +
	"\tascending\x18\x04 \x01(\bR\tascending\"M\n" +
	"\x0eSearchResponse\x12'\n" +
	"\x04hits\x18\x01 \x03(\v2\x13.epochdb.v0.AddrHitR\x04hits\x12\x12\n" +
	"\x04more\x18\x02 \x01(\bR\x04more\"b\n" +
	"\aAddrHit\x12\x15\n" +
	"\x06tx_num\x18\x01 \x01(\x04R\x05txNum\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\x12\x14\n" +
	"\x05roles\x18\x04 \x01(\rR\x05roles\"\x93\x01\n" +
	"\vLogsRequest\x12\x1d\n" +
	"\n" +
	"from_block\x18\x01 \x01(\x04R\tfromBlock\x12\x19\n" +
	"\bto_block\x18\x02 \x01(\x04R\atoBlock\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\fR\taddresses\x12,\n" +
	"\x06topics\x18\x04 \x03(\v2\x14.epochdb.v0.TopicSetR\x06topics\"\"\n" +
	"\bTopicSet\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"3\n" +
	"\fLogsResponse\x12#\n" +
	"\x04logs\x18\x01 \x03(\v2\x0f.epochdb.v0.LogR\x04logs2\xaf\x04\n" +
	"\aEpochDB\x12<\n" +
	"\aGetHead\x12\x17.epochdb.v0.HeadRequest\x1a\x18.epochdb.v0.HeadResponse\x12B\n" +
	"\vStreamHeads\x12\x17.epochdb.v0.HeadRequest\x1a\x18.epochdb.v0.HeadResponse0\x01\x12?\n" +
	"\bGetBlock\x12\x18.epochdb.v0.BlockRequest\x1a\x19.epochdb.v0.BlockResponse\x12Q\n" +
	"\x0eGetTransaction\x12\x1e.epochdb.v0.TransactionRequest\x1a\x1f.epochdb.v0.TransactionResponse\x129\n" +
	"\x04Call\x12\x17.epochdb.v0.CallRequest\x1a\x18.epochdb.v0.CallResponse\x12?\n" +
	"\bGetState\x12\x18.epochdb.v0.StateRequest\x1a\x19.epochdb.v0.StateResponse\x12T\n" +
	"\x1bSearchTransactionsByAddress\x12\x19.epochdb.v0.SearchRequest\x1a\x1a.epochdb.v0.SearchResponse\x12<\n" +
	"\aGetLogs\x12\x17.epochdb.v0.LogsRequest\x1a\x18.epochdb.v0.LogsResponseB+Z)github.com/containerman17/epochdb/grpcapib\x06proto3"

var (
	file_epochdb_proto_rawDescOnce sync.Once
	file_epochdb_proto_rawDescData []byte
)

func file_epochdb_proto_rawDescGZIP() []byte {
	file_epochdb_proto_rawDescOnce.Do(func() {
		file_epochdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_epochdb_proto_rawDesc), len(file_epochdb_proto_rawDesc)))
	})
	return file_epochdb_proto_rawDescData
}

var file_epochdb_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_epochdb_proto_goTypes = []any{
	(*HeadRequest)(nil),         // 0: epochdb.v0.HeadRequest
	(*HeadResponse)(nil),        // 1: epochdb.v0.HeadResponse
	(*BlockRequest)(nil),        // 2: epochdb.v0.BlockRequest
	(*BlockResponse)(nil),       // 3: epochdb.v0.BlockResponse
	(*TransactionRequest)(nil),  // 4: epochdb.v0.TransactionRequest
	(*TransactionResponse)(nil), // 5: epochdb.v0.TransactionResponse
	(*Receipt)(nil),             // 6: epochdb.v0.Receipt
	(*Log)(nil),                 // 7: epochdb.v0.Log
	(*Frame)(nil),               // 8: epochdb.v0.Frame
	(*CallRequest)(nil),         // 9: epochdb.v0.CallRequest
	(*CallResponse)(nil),        // 10: epochdb.v0.CallResponse
	(*StateRequest)(nil),        // 11: epochdb.v0.StateRequest
	(*StateResponse)(nil),       // 12: epochdb.v0.StateResponse
	(*SearchRequest)(nil),       // 13: epochdb.v0.SearchRequest
	(*SearchResponse)(nil),      // 14: epochdb.v0.SearchResponse
	(*AddrHit)(nil),             // 15: epochdb.v0.AddrHit
	(*LogsRequest)(nil),         // 16: epochdb.v0.LogsRequest
	(*TopicSet)(nil),            // 17: epochdb.v0.TopicSet
	(*LogsResponse)(nil),        // 18: epochdb.v0.LogsResponse
}
var file_epochdb_proto_depIdxs = []int32{
	6,  // 0: epochdb.v0.TransactionResponse.receipt:type_name -> epochdb.v0.Receipt
	8,  // 1: epochdb.v0.TransactionResponse.frames:type_name -> epochdb.v0.Frame
	7,  // 2: epochdb.v0.Receipt.logs:type_name -> epochdb.v0.Log
	15, // 3: epochdb.v0.SearchResponse.hits:type_name -> epochdb.v0.AddrHit
	17, // 4: epochdb.v0.LogsRequest.topics:type_name -> epochdb.v0.TopicSet
	7,  // 5: epochdb.v0.LogsResponse.logs:type_name -> epochdb.v0.Log
	0,  // 6: epochdb.v0.EpochDB.GetHead:input_type -> epochdb.v0.HeadRequest
	0,  // 7: epochdb.v0.EpochDB.StreamHeads:input_type -> epochdb.v0.HeadRequest
	2,  // 8: epochdb.v0.EpochDB.GetBlock:input_type -> epochdb.v0.BlockRequest
	4,  // 9: epochdb.v0.EpochDB.GetTransaction:input_type -> epochdb.v0.TransactionRequest
	9,  // 10: epochdb.v0.EpochDB.Call:input_type -> epochdb.v0.CallRequest
	11, // 11: epochdb.v0.EpochDB.GetState:input_type -> epochdb.v0.StateRequest
	13, // 12: epochdb.v0.EpochDB.SearchTransactionsByAddress:input_type -> epochdb.v0.SearchRequest
	16, // 13: epochdb.v0.EpochDB.GetLogs:input_type -> epochdb.v0.LogsRequest
	1,  // 14: epochdb.v0.EpochDB.GetHead:output_type -> epochdb.v0.HeadResponse
	1,  // 15: epochdb.v0.EpochDB.StreamHeads:output_type -> epochdb.v0.HeadResponse
	3,  // 16: epochdb.v0.EpochDB.GetBlock:output_type -> epochdb.v0.BlockResponse
	5,  // 17: epochdb.v0.EpochDB.GetTransaction:output_type -> epochdb.v0.TransactionResponse
	10, // 18: epochdb.v0.EpochDB.Call:output_type -> epochdb.v0.CallResponse
	12, // 19: epochdb.v0.EpochDB.GetState:output_type -> epochdb.v0.StateResponse
	14, // 20: epochdb.v0.EpochDB.SearchTransactionsByAddress:output_type -> epochdb.v0.SearchResponse
	18, // 21: epochdb.v0.EpochDB.GetLogs:output_type -> epochdb.v0.LogsResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_epochdb_proto_init() }
func file_epochdb_proto_init() {
	if File_epochdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_epochdb_proto_rawDesc), len(file_epochdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_epochdb_proto_goTypes,
		DependencyIndexes: file_epochdb_proto_depIdxs,
		MessageInfos:      file_epochdb_proto_msgTypes,
	}.Build()
	File_epochdb_proto = out.File
	file_epochdb_proto_goTypes = nil
	file_epochdb_proto_depIdxs = nil
}
