// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: epochdb.proto

// THE PRIMARY REMOTE API (user ruling 2026-08-12: "gRPC should be the best way
// to access it"). It is a PEER adapter over the core query layer (rpc.Server's
// direct methods), never a proxy to JSON-RPC.
//
// BYTES ARE VERBATIM CONSENSUS RLP wherever the corpus stores RLP: a header, a
// transaction. Nothing is re-serialized into a field-by-field shape that could
// disagree with the stored bytes, and a caller that wants fields decodes with
// the EVM library it already links. Numbers that are not RLP (heights, TxNums,
// gas) are plain integers, and big integers travel as big-endian bytes.

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EpochDB_GetHead_FullMethodName                     = "/epochdb.v0.EpochDB/GetHead"
	EpochDB_StreamHeads_FullMethodName                 = "/epochdb.v0.EpochDB/StreamHeads"
	EpochDB_GetBlock_FullMethodName                    = "/epochdb.v0.EpochDB/GetBlock"
	EpochDB_GetTransaction_FullMethodName              = "/epochdb.v0.EpochDB/GetTransaction"
	EpochDB_Call_FullMethodName                        = "/epochdb.v0.EpochDB/Call"
	EpochDB_GetState_FullMethodName                    = "/epochdb.v0.EpochDB/GetState"
	EpochDB_SearchTransactionsByAddress_FullMethodName = "/epochdb.v0.EpochDB/SearchTransactionsByAddress"
	EpochDB_GetLogs_FullMethodName                     = "/epochdb.v0.EpochDB/GetLogs"
)

// EpochDBClient is the client API for EpochDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EpochDBClient interface {
	// GetHead is the serving frontier: latest, pending and safe at once.
	GetHead(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (*HeadResponse, error)
	// StreamHeads pushes one HeadResponse per new block until the caller goes
	// away.
	StreamHeads(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeadResponse], error)
	GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	GetTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	GetState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	SearchTransactionsByAddress(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error)
}

type epochDBClient struct {
	cc grpc.ClientConnInterface
}

func NewEpochDBClient(cc grpc.ClientConnInterface) EpochDBClient {
	return &epochDBClient{cc}
}

func (c *epochDBClient) GetHead(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (*HeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeadResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) StreamHeads(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EpochDB_ServiceDesc.Streams[0], EpochDB_StreamHeads_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeadRequest, HeadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpochDB_StreamHeadsClient = grpc.ServerStreamingClient[HeadResponse]

func (c *epochDBClient) GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, EpochDB_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) SearchTransactionsByAddress(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, EpochDB_SearchTransactionsByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EpochDBServer is the server API for EpochDB service.
// All implementations must embed UnimplementedEpochDBServer
// for forward compatibility.
type EpochDBServer interface {
	// GetHead is the serving frontier: latest, pending and safe at once.
	GetHead(context.Context, *HeadRequest) (*HeadResponse, error)
	// StreamHeads pushes one HeadResponse per new block until the caller goes
	// away.
	StreamHeads(*HeadRequest, grpc.ServerStreamingServer[HeadResponse]) error
	GetBlock(context.Context, *BlockRequest) (*BlockResponse, error)
	GetTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
	Call(context.Context, *CallRequest) (*CallResponse, error)
	GetState(context.Context, *StateRequest) (*StateResponse, error)
	SearchTransactionsByAddress(context.Context, *SearchRequest) (*SearchResponse, error)
	GetLogs(context.Context, *LogsRequest) (*LogsResponse, error)
	mustEmbedUnimplementedEpochDBServer()
}

// UnimplementedEpochDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEpochDBServer struct{}

func (UnimplementedEpochDBServer) GetHead(context.Context, *HeadRequest) (*HeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHead not implemented")
}
func (UnimplementedEpochDBServer) StreamHeads(*HeadRequest, grpc.ServerStreamingServer[HeadResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamHeads not implemented")
}
func (UnimplementedEpochDBServer) GetBlock(context.Context, *BlockRequest) (*BlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedEpochDBServer) GetTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedEpochDBServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedEpochDBServer) GetState(context.Context, *StateRequest) (*StateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedEpochDBServer) SearchTransactionsByAddress(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTransactionsByAddress not implemented")
}
func (UnimplementedEpochDBServer) GetLogs(context.Context, *LogsRequest) (*LogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedEpochDBServer) mustEmbedUnimplementedEpochDBServer() {}
func (UnimplementedEpochDBServer) testEmbeddedByValue()                 {}

// UnsafeEpochDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EpochDBServer will
// result in compilation errors.
type UnsafeEpochDBServer interface {
	mustEmbedUnimplementedEpochDBServer()
}

func RegisterEpochDBServer(s grpc.ServiceRegistrar, srv EpochDBServer) {
	// If the following call panics, it indicates UnimplementedEpochDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EpochDB_ServiceDesc, srv)
}

func _EpochDB_GetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetHead(ctx, req.(*HeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_StreamHeads_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HeadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EpochDBServer).StreamHeads(m, &grpc.GenericServerStream[HeadRequest, HeadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpochDB_StreamHeadsServer = grpc.ServerStreamingServer[HeadResponse]

func _EpochDB_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetBlock(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_SearchTransactionsByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).SearchTransactionsByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_SearchTransactionsByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).SearchTransactionsByAddress(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetLogs(ctx, req.(*LogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EpochDB_ServiceDesc is the grpc.ServiceDesc for EpochDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EpochDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "epochdb.v0.EpochDB",
	HandlerType: (*EpochDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHead",
			Handler:    _EpochDB_GetHead_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _EpochDB_GetBlock_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _EpochDB_GetTransaction_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _EpochDB_Call_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _EpochDB_GetState_Handler,
		},
		{
			MethodName: "SearchTransactionsByAddress",
			Handler:    _EpochDB_SearchTransactionsByAddress_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _EpochDB_GetLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHeads",
			Handler:       _EpochDB_StreamHeads_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "epochdb.proto",
}
