// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: epochdb.proto

// THE PRIMARY REMOTE API (user ruling 2026-08-12: "gRPC should be the best way
// to access it"). It is a PEER adapter over the core query layer (rpc.Server's
// direct methods), never a proxy to JSON-RPC.
//
// IT COVERS THE WHOLE CAPABILITY SET. Everything the node can actually do is
// reachable here; the JSON-RPC surface's 90-odd method spellings collapse onto
// these methods because most of that count is spelling variety over one
// primitive (by-number and by-hash, filter-install plus poll, four names for
// the same fee answer). What is NOT here is the permanent refusal set, and it
// is not here BY ABSENCE PLUS A NAMED REASON: GetNodeInfo lists every refused
// capability with the reason, and calling one of them is Unimplemented rather
// than a plausible empty answer (DESIGN: "null means not on this chain, never
// I could not read it").
//
// BYTES ARE VERBATIM CONSENSUS RLP wherever the corpus stores RLP: a header, a
// transaction, a container. Nothing is re-serialized into a field-by-field
// shape that could disagree with the stored bytes, and a caller that wants
// fields decodes with the EVM library it already links. Numbers that are not
// RLP (heights, TxNums, gas) are plain integers, and big integers travel as
// big-endian bytes. A TRACER'S CONFIG AND RESULT ARE JSON, verbatim, because
// that is what a geth tracer takes and emits.

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EpochDB_GetHead_FullMethodName                     = "/epochdb.v0.EpochDB/GetHead"
	EpochDB_StreamHeads_FullMethodName                 = "/epochdb.v0.EpochDB/StreamHeads"
	EpochDB_GetNodeInfo_FullMethodName                 = "/epochdb.v0.EpochDB/GetNodeInfo"
	EpochDB_GetBlock_FullMethodName                    = "/epochdb.v0.EpochDB/GetBlock"
	EpochDB_GetTransaction_FullMethodName              = "/epochdb.v0.EpochDB/GetTransaction"
	EpochDB_GetState_FullMethodName                    = "/epochdb.v0.EpochDB/GetState"
	EpochDB_Call_FullMethodName                        = "/epochdb.v0.EpochDB/Call"
	EpochDB_EstimateGas_FullMethodName                 = "/epochdb.v0.EpochDB/EstimateGas"
	EpochDB_Trace_FullMethodName                       = "/epochdb.v0.EpochDB/Trace"
	EpochDB_GetLogs_FullMethodName                     = "/epochdb.v0.EpochDB/GetLogs"
	EpochDB_StreamLogs_FullMethodName                  = "/epochdb.v0.EpochDB/StreamLogs"
	EpochDB_StreamTransactions_FullMethodName          = "/epochdb.v0.EpochDB/StreamTransactions"
	EpochDB_SearchTransactionsByAddress_FullMethodName = "/epochdb.v0.EpochDB/SearchTransactionsByAddress"
	EpochDB_GetContractCreator_FullMethodName          = "/epochdb.v0.EpochDB/GetContractCreator"
	EpochDB_GetLogsByEmitter_FullMethodName            = "/epochdb.v0.EpochDB/GetLogsByEmitter"
	EpochDB_GetLogsByTopicValue_FullMethodName         = "/epochdb.v0.EpochDB/GetLogsByTopicValue"
	EpochDB_GetTopicGroups_FullMethodName              = "/epochdb.v0.EpochDB/GetTopicGroups"
	EpochDB_GetTokenTransfersByHolder_FullMethodName   = "/epochdb.v0.EpochDB/GetTokenTransfersByHolder"
	EpochDB_GetTokenTransfersByContract_FullMethodName = "/epochdb.v0.EpochDB/GetTokenTransfersByContract"
	EpochDB_GetTokenContracts_FullMethodName           = "/epochdb.v0.EpochDB/GetTokenContracts"
	EpochDB_GetFeeHistory_FullMethodName               = "/epochdb.v0.EpochDB/GetFeeHistory"
	EpochDB_GetGasPrice_FullMethodName                 = "/epochdb.v0.EpochDB/GetGasPrice"
)

// EpochDBClient is the client API for EpochDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EpochDBClient interface {
	// GetHead is the serving frontier: latest, pending and safe at once.
	GetHead(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (*HeadResponse, error)
	// StreamHeads pushes one HeadResponse per new block until the caller goes
	// away.
	StreamHeads(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeadResponse], error)
	// GetNodeInfo is the chain, the build, the sync state and the refusal list.
	GetNodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoResponse, error)
	GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	GetTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	GetState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	EstimateGas(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*EstimateGasResponse, error)
	// Trace re-executes a transaction, a block or a call under a named tracer.
	Trace(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceResponse, error)
	GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error)
	// StreamLogs REPLACES the whole poll-and-filter-id model: there is nothing
	// to install and nothing to uninstall, the stream IS the filter, and
	// cancelling it is uninstalling it.
	StreamLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error)
	// StreamTransactions pushes each new block's transactions. There is no
	// mempool on this node, so these are ACCEPTED transactions, never pending
	// ones.
	StreamTransactions(ctx context.Context, in *StreamTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransactionBatch], error)
	SearchTransactionsByAddress(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetContractCreator(ctx context.Context, in *ContractCreatorRequest, opts ...grpc.CallOption) (*ContractCreatorResponse, error)
	// The posting-list log reads (rpc/tokens.go): what eth_getLogs cannot
	// answer in one bounded call. Keyset-paged over TxNum like the search;
	// the page is cut on transactions, never inside one.
	GetLogsByEmitter(ctx context.Context, in *LogsByEmitterRequest, opts ...grpc.CallOption) (*PagedLogsResponse, error)
	GetLogsByTopicValue(ctx context.Context, in *LogsByTopicValueRequest, opts ...grpc.CallOption) (*PagedLogsResponse, error)
	GetTopicGroups(ctx context.Context, in *TopicGroupsRequest, opts ...grpc.CallOption) (*TopicGroupsResponse, error)
	// The ERC-20/721/1155 shortcuts: fixed signatures and positions over the two
	// reads above. standard is erc20 | erc721 | erc1155.
	GetTokenTransfersByHolder(ctx context.Context, in *TokenTransfersRequest, opts ...grpc.CallOption) (*PagedLogsResponse, error)
	GetTokenTransfersByContract(ctx context.Context, in *TokenTransfersRequest, opts ...grpc.CallOption) (*PagedLogsResponse, error)
	GetTokenContracts(ctx context.Context, in *TokenContractsRequest, opts ...grpc.CallOption) (*TokenContractsResponse, error)
	GetFeeHistory(ctx context.Context, in *FeeHistoryRequest, opts ...grpc.CallOption) (*FeeHistoryResponse, error)
	// GetGasPrice is the whole fee-suggestion surface out of one sample.
	GetGasPrice(ctx context.Context, in *GasPriceRequest, opts ...grpc.CallOption) (*GasPriceResponse, error)
}

type epochDBClient struct {
	cc grpc.ClientConnInterface
}

func NewEpochDBClient(cc grpc.ClientConnInterface) EpochDBClient {
	return &epochDBClient{cc}
}

func (c *epochDBClient) GetHead(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (*HeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeadResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) StreamHeads(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EpochDB_ServiceDesc.Streams[0], EpochDB_StreamHeads_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeadRequest, HeadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpochDB_StreamHeadsClient = grpc.ServerStreamingClient[HeadResponse]

func (c *epochDBClient) GetNodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfoResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, EpochDB_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) EstimateGas(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*EstimateGasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateGasResponse)
	err := c.cc.Invoke(ctx, EpochDB_EstimateGas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) Trace(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceResponse)
	err := c.cc.Invoke(ctx, EpochDB_Trace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) StreamLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EpochDB_ServiceDesc.Streams[1], EpochDB_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpochDB_StreamLogsClient = grpc.ServerStreamingClient[LogsResponse]

func (c *epochDBClient) StreamTransactions(ctx context.Context, in *StreamTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransactionBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EpochDB_ServiceDesc.Streams[2], EpochDB_StreamTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTransactionsRequest, TransactionBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpochDB_StreamTransactionsClient = grpc.ServerStreamingClient[TransactionBatch]

func (c *epochDBClient) SearchTransactionsByAddress(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, EpochDB_SearchTransactionsByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetContractCreator(ctx context.Context, in *ContractCreatorRequest, opts ...grpc.CallOption) (*ContractCreatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractCreatorResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetContractCreator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetLogsByEmitter(ctx context.Context, in *LogsByEmitterRequest, opts ...grpc.CallOption) (*PagedLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PagedLogsResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetLogsByEmitter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetLogsByTopicValue(ctx context.Context, in *LogsByTopicValueRequest, opts ...grpc.CallOption) (*PagedLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PagedLogsResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetLogsByTopicValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetTopicGroups(ctx context.Context, in *TopicGroupsRequest, opts ...grpc.CallOption) (*TopicGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicGroupsResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetTopicGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetTokenTransfersByHolder(ctx context.Context, in *TokenTransfersRequest, opts ...grpc.CallOption) (*PagedLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PagedLogsResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetTokenTransfersByHolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetTokenTransfersByContract(ctx context.Context, in *TokenTransfersRequest, opts ...grpc.CallOption) (*PagedLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PagedLogsResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetTokenTransfersByContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetTokenContracts(ctx context.Context, in *TokenContractsRequest, opts ...grpc.CallOption) (*TokenContractsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenContractsResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetTokenContracts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetFeeHistory(ctx context.Context, in *FeeHistoryRequest, opts ...grpc.CallOption) (*FeeHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeeHistoryResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetFeeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epochDBClient) GetGasPrice(ctx context.Context, in *GasPriceRequest, opts ...grpc.CallOption) (*GasPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GasPriceResponse)
	err := c.cc.Invoke(ctx, EpochDB_GetGasPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EpochDBServer is the server API for EpochDB service.
// All implementations must embed UnimplementedEpochDBServer
// for forward compatibility.
type EpochDBServer interface {
	// GetHead is the serving frontier: latest, pending and safe at once.
	GetHead(context.Context, *HeadRequest) (*HeadResponse, error)
	// StreamHeads pushes one HeadResponse per new block until the caller goes
	// away.
	StreamHeads(*HeadRequest, grpc.ServerStreamingServer[HeadResponse]) error
	// GetNodeInfo is the chain, the build, the sync state and the refusal list.
	GetNodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoResponse, error)
	GetBlock(context.Context, *BlockRequest) (*BlockResponse, error)
	GetTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
	GetState(context.Context, *StateRequest) (*StateResponse, error)
	Call(context.Context, *CallRequest) (*CallResponse, error)
	EstimateGas(context.Context, *CallRequest) (*EstimateGasResponse, error)
	// Trace re-executes a transaction, a block or a call under a named tracer.
	Trace(context.Context, *TraceRequest) (*TraceResponse, error)
	GetLogs(context.Context, *LogsRequest) (*LogsResponse, error)
	// StreamLogs REPLACES the whole poll-and-filter-id model: there is nothing
	// to install and nothing to uninstall, the stream IS the filter, and
	// cancelling it is uninstalling it.
	StreamLogs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error
	// StreamTransactions pushes each new block's transactions. There is no
	// mempool on this node, so these are ACCEPTED transactions, never pending
	// ones.
	StreamTransactions(*StreamTransactionsRequest, grpc.ServerStreamingServer[TransactionBatch]) error
	SearchTransactionsByAddress(context.Context, *SearchRequest) (*SearchResponse, error)
	GetContractCreator(context.Context, *ContractCreatorRequest) (*ContractCreatorResponse, error)
	// The posting-list log reads (rpc/tokens.go): what eth_getLogs cannot
	// answer in one bounded call. Keyset-paged over TxNum like the search;
	// the page is cut on transactions, never inside one.
	GetLogsByEmitter(context.Context, *LogsByEmitterRequest) (*PagedLogsResponse, error)
	GetLogsByTopicValue(context.Context, *LogsByTopicValueRequest) (*PagedLogsResponse, error)
	GetTopicGroups(context.Context, *TopicGroupsRequest) (*TopicGroupsResponse, error)
	// The ERC-20/721/1155 shortcuts: fixed signatures and positions over the two
	// reads above. standard is erc20 | erc721 | erc1155.
	GetTokenTransfersByHolder(context.Context, *TokenTransfersRequest) (*PagedLogsResponse, error)
	GetTokenTransfersByContract(context.Context, *TokenTransfersRequest) (*PagedLogsResponse, error)
	GetTokenContracts(context.Context, *TokenContractsRequest) (*TokenContractsResponse, error)
	GetFeeHistory(context.Context, *FeeHistoryRequest) (*FeeHistoryResponse, error)
	// GetGasPrice is the whole fee-suggestion surface out of one sample.
	GetGasPrice(context.Context, *GasPriceRequest) (*GasPriceResponse, error)
	mustEmbedUnimplementedEpochDBServer()
}

// UnimplementedEpochDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEpochDBServer struct{}

func (UnimplementedEpochDBServer) GetHead(context.Context, *HeadRequest) (*HeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHead not implemented")
}
func (UnimplementedEpochDBServer) StreamHeads(*HeadRequest, grpc.ServerStreamingServer[HeadResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamHeads not implemented")
}
func (UnimplementedEpochDBServer) GetNodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedEpochDBServer) GetBlock(context.Context, *BlockRequest) (*BlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedEpochDBServer) GetTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedEpochDBServer) GetState(context.Context, *StateRequest) (*StateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedEpochDBServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedEpochDBServer) EstimateGas(context.Context, *CallRequest) (*EstimateGasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateGas not implemented")
}
func (UnimplementedEpochDBServer) Trace(context.Context, *TraceRequest) (*TraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Trace not implemented")
}
func (UnimplementedEpochDBServer) GetLogs(context.Context, *LogsRequest) (*LogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedEpochDBServer) StreamLogs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedEpochDBServer) StreamTransactions(*StreamTransactionsRequest, grpc.ServerStreamingServer[TransactionBatch]) error {
	return status.Error(codes.Unimplemented, "method StreamTransactions not implemented")
}
func (UnimplementedEpochDBServer) SearchTransactionsByAddress(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTransactionsByAddress not implemented")
}
func (UnimplementedEpochDBServer) GetContractCreator(context.Context, *ContractCreatorRequest) (*ContractCreatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContractCreator not implemented")
}
func (UnimplementedEpochDBServer) GetLogsByEmitter(context.Context, *LogsByEmitterRequest) (*PagedLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogsByEmitter not implemented")
}
func (UnimplementedEpochDBServer) GetLogsByTopicValue(context.Context, *LogsByTopicValueRequest) (*PagedLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogsByTopicValue not implemented")
}
func (UnimplementedEpochDBServer) GetTopicGroups(context.Context, *TopicGroupsRequest) (*TopicGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopicGroups not implemented")
}
func (UnimplementedEpochDBServer) GetTokenTransfersByHolder(context.Context, *TokenTransfersRequest) (*PagedLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenTransfersByHolder not implemented")
}
func (UnimplementedEpochDBServer) GetTokenTransfersByContract(context.Context, *TokenTransfersRequest) (*PagedLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenTransfersByContract not implemented")
}
func (UnimplementedEpochDBServer) GetTokenContracts(context.Context, *TokenContractsRequest) (*TokenContractsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenContracts not implemented")
}
func (UnimplementedEpochDBServer) GetFeeHistory(context.Context, *FeeHistoryRequest) (*FeeHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeeHistory not implemented")
}
func (UnimplementedEpochDBServer) GetGasPrice(context.Context, *GasPriceRequest) (*GasPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGasPrice not implemented")
}
func (UnimplementedEpochDBServer) mustEmbedUnimplementedEpochDBServer() {}
func (UnimplementedEpochDBServer) testEmbeddedByValue()                 {}

// UnsafeEpochDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EpochDBServer will
// result in compilation errors.
type UnsafeEpochDBServer interface {
	mustEmbedUnimplementedEpochDBServer()
}

func RegisterEpochDBServer(s grpc.ServiceRegistrar, srv EpochDBServer) {
	// If the following call panics, it indicates UnimplementedEpochDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EpochDB_ServiceDesc, srv)
}

func _EpochDB_GetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetHead(ctx, req.(*HeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_StreamHeads_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HeadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EpochDBServer).StreamHeads(m, &grpc.GenericServerStream[HeadRequest, HeadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpochDB_StreamHeadsServer = grpc.ServerStreamingServer[HeadResponse]

func _EpochDB_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetNodeInfo(ctx, req.(*NodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetBlock(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_EstimateGas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).EstimateGas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_EstimateGas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).EstimateGas(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_Trace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).Trace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_Trace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).Trace(ctx, req.(*TraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetLogs(ctx, req.(*LogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EpochDBServer).StreamLogs(m, &grpc.GenericServerStream[LogsRequest, LogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpochDB_StreamLogsServer = grpc.ServerStreamingServer[LogsResponse]

func _EpochDB_StreamTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EpochDBServer).StreamTransactions(m, &grpc.GenericServerStream[StreamTransactionsRequest, TransactionBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpochDB_StreamTransactionsServer = grpc.ServerStreamingServer[TransactionBatch]

func _EpochDB_SearchTransactionsByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).SearchTransactionsByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_SearchTransactionsByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).SearchTransactionsByAddress(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetContractCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractCreatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetContractCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetContractCreator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetContractCreator(ctx, req.(*ContractCreatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetLogsByEmitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsByEmitterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetLogsByEmitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetLogsByEmitter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetLogsByEmitter(ctx, req.(*LogsByEmitterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetLogsByTopicValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsByTopicValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetLogsByTopicValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetLogsByTopicValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetLogsByTopicValue(ctx, req.(*LogsByTopicValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetTopicGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetTopicGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetTopicGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetTopicGroups(ctx, req.(*TopicGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetTokenTransfersByHolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetTokenTransfersByHolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetTokenTransfersByHolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetTokenTransfersByHolder(ctx, req.(*TokenTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetTokenTransfersByContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetTokenTransfersByContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetTokenTransfersByContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetTokenTransfersByContract(ctx, req.(*TokenTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetTokenContracts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenContractsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetTokenContracts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetTokenContracts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetTokenContracts(ctx, req.(*TokenContractsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetFeeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeeHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetFeeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetFeeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetFeeHistory(ctx, req.(*FeeHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpochDB_GetGasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GasPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpochDBServer).GetGasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpochDB_GetGasPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpochDBServer).GetGasPrice(ctx, req.(*GasPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EpochDB_ServiceDesc is the grpc.ServiceDesc for EpochDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EpochDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "epochdb.v0.EpochDB",
	HandlerType: (*EpochDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHead",
			Handler:    _EpochDB_GetHead_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _EpochDB_GetNodeInfo_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _EpochDB_GetBlock_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _EpochDB_GetTransaction_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _EpochDB_GetState_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _EpochDB_Call_Handler,
		},
		{
			MethodName: "EstimateGas",
			Handler:    _EpochDB_EstimateGas_Handler,
		},
		{
			MethodName: "Trace",
			Handler:    _EpochDB_Trace_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _EpochDB_GetLogs_Handler,
		},
		{
			MethodName: "SearchTransactionsByAddress",
			Handler:    _EpochDB_SearchTransactionsByAddress_Handler,
		},
		{
			MethodName: "GetContractCreator",
			Handler:    _EpochDB_GetContractCreator_Handler,
		},
		{
			MethodName: "GetLogsByEmitter",
			Handler:    _EpochDB_GetLogsByEmitter_Handler,
		},
		{
			MethodName: "GetLogsByTopicValue",
			Handler:    _EpochDB_GetLogsByTopicValue_Handler,
		},
		{
			MethodName: "GetTopicGroups",
			Handler:    _EpochDB_GetTopicGroups_Handler,
		},
		{
			MethodName: "GetTokenTransfersByHolder",
			Handler:    _EpochDB_GetTokenTransfersByHolder_Handler,
		},
		{
			MethodName: "GetTokenTransfersByContract",
			Handler:    _EpochDB_GetTokenTransfersByContract_Handler,
		},
		{
			MethodName: "GetTokenContracts",
			Handler:    _EpochDB_GetTokenContracts_Handler,
		},
		{
			MethodName: "GetFeeHistory",
			Handler:    _EpochDB_GetFeeHistory_Handler,
		},
		{
			MethodName: "GetGasPrice",
			Handler:    _EpochDB_GetGasPrice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHeads",
			Handler:       _EpochDB_StreamHeads_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _EpochDB_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTransactions",
			Handler:       _EpochDB_StreamTransactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "epochdb.proto",
}
