// Generated by cbindgen from rust/prunedffi. Do not edit.

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define ACCOUNT 3

#define BRANCH 1

#define EXT 2

#define FREE 0

#define NODE_SIZE 144

#define NONE UINT32_MAX

#define OP_ACCOUNT 1

#define OP_DELETE 2

#define OP_SLOT 3

/**
 * Account row as the Go side sends it: nonce (8, big-endian), balance (32,
 * big-endian), code hash (32).
 */
#define ROW 72

#define SLOT 4

typedef struct Db Db;

typedef struct pf_status {
  int32_t code;
  char *msg;
} pf_status;

typedef struct pf_head {
  uint8_t root[32];
  uint8_t block[32];
  uint64_t height;
} pf_head;

typedef struct pf_value {
  /**
   * 0 when the key is absent.
   */
  uint32_t len;
  uint8_t data[72];
} pf_value;

typedef uint8_t Hash[32];

/**
 * keccak256(rlp("")) = keccak256(0x80), the root of an empty trie.
 */
#define EMPTY_ROOT { 86, 232, 31, 23, 27, 204, 85, 166, 255, 131, 69, 230, 146, 192, 248, 110, 91, 72, 224, 27, 153, 108, 173, 192, 1, 98, 47, 181, 227, 99, 180, 33, }

/**
 * Forces a checkpoint (tests).
 */
struct pf_status pf_checkpoint(struct Db *db);

struct pf_status pf_clear_all(struct Db *db);

/**
 * Closes and frees the handle.
 */
struct pf_status pf_close(struct Db *db);

struct pf_status pf_commit(struct Db *db, const uint8_t *root);

void pf_current(struct Db *db, struct pf_head *out);

void pf_free_status(struct pf_status s);

struct pf_status pf_get_account(struct Db *db,
                                const uint8_t *root,
                                const uint8_t *key,
                                struct pf_value *out);

struct pf_status pf_get_storage(struct Db *db,
                                const uint8_t *root,
                                const uint8_t *key,
                                const uint8_t *slot,
                                struct pf_value *out);

/**
 * Code 1 when no retained revision has this root.
 */
struct pf_status pf_has_root(struct Db *db, const uint8_t *root);

/**
 * Opens or creates the state directory. Zero values select the defaults.
 */
struct pf_status pf_open(const char *dir,
                         uint64_t retain,
                         uint64_t commit_interval,
                         int64_t journal_limit,
                         struct Db **out);

/**
 * Computes the root of applying ops to the revision at parent and keeps the
 * proposal for `pf_update`.
 */
struct pf_status pf_propose(struct Db *db,
                            const uint8_t *parent,
                            const uint8_t *ops,
                            size_t ops_len,
                            uint8_t *out_root);

void pf_set_hash_and_height(struct Db *db, const uint8_t *hash_, uint64_t height);

/**
 * Bytes held by the node arena.
 */
uint64_t pf_size(struct Db *db);

struct pf_status pf_update(struct Db *db,
                           const uint8_t *root,
                           const uint8_t *parent,
                           uint64_t height,
                           const uint8_t *parent_hash,
                           const uint8_t *block_hash);
