/* epochdb engine C ABI. Generated by cbindgen from rs/ffi/src/lib.rs; ABI.md is the contract. */

#ifndef EPOCHDB_ENGINE_H
#define EPOCHDB_ENGINE_H

#include <stdint.h>
#include <stddef.h>

#define EPOCHDB_OK 0

/**
 * The operation failed; `epochdb_last_error` has the text.
 */
#define EPOCHDB_ERR -1

/**
 * A null pointer, a bad length or an unknown enum value.
 */
#define EPOCHDB_EINVAL -2

/**
 * The block id (or height) is unknown to the engine.
 */
#define EPOCHDB_ENOTFOUND -3

/**
 * A Rust panic was caught at the boundary; the engine should be closed.
 */
#define EPOCHDB_EPANIC -4

/**
 * One open chain.
 */
typedef struct epochdb_engine epochdb_engine;

/**
 * A Rust-owned byte buffer. `ptr` is null when `len` is 0. Free exactly
 * once with `epochdb_buf_free`.
 */
typedef struct epochdb_buf {
  uint8_t *ptr;
  size_t len;
} epochdb_buf;

typedef struct epochdb_block_meta {
  /**
   * keccak(header): the block id.
   */
  uint8_t id[32];
  uint8_t parent[32];
  uint64_t height;
  /**
   * Unix seconds.
   */
  uint64_t timestamp;
} epochdb_block_meta;

typedef struct epochdb_verify_out {
  uint8_t state_root[32];
  uint64_t gas_used;
  uint64_t tx_count;
} epochdb_verify_out;

typedef struct epochdb_build_out {
  /**
   * The inner block RLP.
   */
  struct epochdb_buf block_bytes;
  uint8_t id[32];
  uint64_t gas_used;
  uint64_t included_count;
  /**
   * One byte per candidate: 0 included, 1 nonce too low (skipped), 2 the
   * tx failed (sender popped), 3 an earlier tx of the sender was popped,
   * 4 no gas left for it (popped), 5 over the 1800 KiB size target
   * (popped), 6 not reached (the loop stopped under 21,000 gas).
   */
  struct epochdb_buf skipped;
  /**
   * 1 when the gas limit is not filled and every candidate was considered.
   */
  uint8_t needs_more;
  /**
   * Nanoseconds per phase: 0 candidate decode, 1 lock + parent + header
   * template, 2 sender recovery, 3 execution, 4 fee check + finish, 5
   * state root, 6 assemble + hash, 7 parsed-cache insert, 8 tree insert,
   * 9 result copy into the out buffers.
   */
  uint64_t phase_ns[10];
} epochdb_build_out;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Opens (or reopens) the chain under `data_dir`. Returns null on failure
 * with the message in `err` (free it). `config_json` takes the plugin's
 * keys (roll-budget-mb, roll-every-blocks, s3-*, min-delay-target, ...).
 */
struct epochdb_engine *epochdb_open(const uint8_t *data_dir,
                                    size_t data_dir_len,
                                    const uint8_t *genesis_json,
                                    size_t genesis_len,
                                    const uint8_t *upgrade_json,
                                    size_t upgrade_len,
                                    const uint8_t *config_json,
                                    size_t config_len,
                                    const uint8_t *chain_id,
                                    const uint8_t *subnet_id,
                                    uint32_t network_id,
                                    struct epochdb_buf *err);

/**
 * Shutdown (rolls finished, the store synced and closed) and free.
 */
void epochdb_close(struct epochdb_engine *e);

/**
 * The text of the last error this engine reported (empty if none).
 */
int epochdb_last_error(const struct epochdb_engine *e, struct epochdb_buf *out);

/**
 * snow.State: 1 = bootstrapping (roots checked one block behind), 2 =
 * normal op (the root inside verify, build allowed).
 */
int epochdb_set_state(struct epochdb_engine *e, uint32_t state);

/**
 * Decodes a block (the inner RLP; a proposervm container is accepted too),
 * recovers senders, caches it by id.
 */
int epochdb_parse(struct epochdb_engine *e,
                  const uint8_t *block,
                  size_t len,
                  struct epochdb_block_meta *out);

/**
 * Verify by id (parsed or built earlier). `pchain_height` 0 = none.
 */
int epochdb_verify(struct epochdb_engine *e,
                   const uint8_t *id,
                   uint64_t pchain_height,
                   struct epochdb_verify_out *out);

int epochdb_accept(struct epochdb_engine *e, const uint8_t *id);

int epochdb_reject(struct epochdb_engine *e, const uint8_t *id);

int epochdb_last_accepted(struct epochdb_engine *e, uint8_t *id, uint64_t *height);

int epochdb_block_id_at_height(struct epochdb_engine *e, uint64_t height, uint8_t *id);

/**
 * The block's bytes as they were handed in (verified or accepted); the
 * genesis is assembled as `[header, [], []]`.
 */
int epochdb_get_block(struct epochdb_engine *e, const uint8_t *id, struct epochdb_buf *out);

/**
 * Builds a block on `parent_id` (zero or the head's id = the accepted head;
 * else a verified block) at `timestamp_ms` (Unix milliseconds) from `txs`
 * in the miner's order, with their senders (`senders`: 20 bytes each, or
 * null: the engine recovers them); the result is a verified pending block
 * whose later verify is a lookup. See ABI.md for the semantics.
 */
int epochdb_build(struct epochdb_engine *e,
                  const uint8_t *parent_id,
                  uint64_t timestamp_ms,
                  const uint8_t *coinbase,
                  uint64_t pchain_height,
                  const uint8_t *txs,
                  size_t txs_len,
                  const uint8_t *senders,
                  size_t senders_len,
                  struct epochdb_build_out *out);

/**
 * nonce (u64 LE) and balance (32 bytes BE) of `n` addresses at the state of
 * `block_id` (zero = the accepted head; a verified block's id = its pending state).
 */
int epochdb_account_state(struct epochdb_engine *e,
                          const uint8_t *addrs,
                          size_t n,
                          const uint8_t *block_id,
                          struct epochdb_buf *out);

/**
 * The accepted head's header RLP (the genesis header before any accept).
 */
int epochdb_head_header(struct epochdb_engine *e, struct epochdb_buf *out);

/**
 * One JSON-RPC request body (single or batch) in, the response body out.
 */
int epochdb_rpc(struct epochdb_engine *e, const uint8_t *body, size_t len, struct epochdb_buf *out);

/**
 * `{"height":..,"root-checked":..,"normal-op":..}`.
 */
int epochdb_health(struct epochdb_engine *e, struct epochdb_buf *out);

/**
 * Frees a buffer returned by any function above (a null / empty one is fine).
 */
void epochdb_buf_free(struct epochdb_buf *b);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EPOCHDB_ENGINE_H */
