/* epochdb_engine.h: the block-granular C ABI of the Rust engine, derived from
 * VALIDATOR_PLAN.md. The real header is generated by cbindgen into rs/ffi/;
 * this copy is what the Go shell compiles against until it lands (and what
 * the stub implements). Every function returns 0 on success, negative on
 * error; epochdb_last_error gives the text. Buffers are Rust-owned, freed by
 * epochdb_buf_free. */
#ifndef EPOCHDB_ENGINE_H
#define EPOCHDB_ENGINE_H
#include <stddef.h>
#include <stdint.h>

typedef struct epochdb_engine epochdb_engine;

typedef struct { uint8_t *ptr; size_t len; } epochdb_buf;

typedef struct {
  uint8_t id[32];
  uint8_t parent[32];
  uint64_t height;
  uint64_t timestamp;
} epochdb_block_meta;

typedef struct {
  uint8_t state_root[32];
  uint64_t gas_used;
  uint64_t tx_count;
} epochdb_verify_out;

typedef struct {
  epochdb_buf block_bytes;
  uint8_t id[32];
  uint64_t gas_used;
  uint64_t included_count;
  epochdb_buf skipped;
  uint8_t needs_more;
  uint64_t phase_ns[10];
} epochdb_build_out;

epochdb_engine *epochdb_open(const uint8_t *data_dir, size_t data_dir_len,
                             const uint8_t *genesis_json, size_t genesis_len,
                             const uint8_t *upgrade_json, size_t upgrade_len,
                             const uint8_t *config_json, size_t config_len,
                             const uint8_t chain_id[32], const uint8_t subnet_id[32],
                             uint32_t network_id, epochdb_buf *err);
void epochdb_close(epochdb_engine *);
int epochdb_set_state(epochdb_engine *, uint32_t state);
int epochdb_parse(epochdb_engine *, const uint8_t *block, size_t len, epochdb_block_meta *out);
int epochdb_verify(epochdb_engine *, const uint8_t id[32], uint64_t pchain_height, epochdb_verify_out *out);
int epochdb_accept(epochdb_engine *, const uint8_t id[32]);
int epochdb_reject(epochdb_engine *, const uint8_t id[32]);
int epochdb_last_accepted(epochdb_engine *, uint8_t id[32], uint64_t *height);
int epochdb_block_id_at_height(epochdb_engine *, uint64_t height, uint8_t id[32]);
int epochdb_get_block(epochdb_engine *, const uint8_t id[32], epochdb_buf *block_bytes);
/* timestamp_ms: wall clock in milliseconds; the engine derives Time (s) and,
 * under Granite, TimeMilliseconds, and clamps to the parent's rules. */
int epochdb_build(epochdb_engine *, const uint8_t parent_id[32], uint64_t timestamp_ms,
                  const uint8_t coinbase[20], uint64_t pchain_height,
                  const uint8_t *txs, size_t txs_len, const uint8_t *senders, size_t senders_len, epochdb_build_out *out);
int epochdb_account_state(epochdb_engine *, const uint8_t *addrs, size_t n,
                          const uint8_t block_id[32], epochdb_buf *out);
int epochdb_head_header(epochdb_engine *, epochdb_buf *header_rlp);
int epochdb_rpc(epochdb_engine *, const uint8_t *body, size_t len, epochdb_buf *response);
int epochdb_health(epochdb_engine *, epochdb_buf *json);
int epochdb_last_error(epochdb_engine *, epochdb_buf *text);
void epochdb_buf_free(epochdb_buf *);

#endif
